fix bug: com.jolbox.bonecp 依赖于 guava 20.0: Caused by: java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/Object;)Lcom/google/common/base/Objects$ToStringHelper;  at com.jolbox.bonecp.ConnectionHandle.toString(ConnectionHandle.java:1711)